merged update && sync

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -1,30 +1,38 @@
 #! /bin/bash
 set -e
 
-cd $(dirname $0)
+start_pwd="$PWD"
+\cd $(dirname $0)
 
-syncfiles="bashrc emacs gitconfig screenrc vimrc zshrc"
-for dotfilename in $syncfiles; do
+if type git &>/dev/null; then
+  \git stash save -q
+  \git pull -q
+  \git stash pop -q 2>/dev/null
+else
+  echo "Could not update since git is not available" >&2
+fi
+
+for dotfilename in bashrc emacs gitconfig screenrc vimrc zshrc; do
   srcname="$PWD/$dotfilename"
   dstname="$HOME/.$dotfilename"
 
-  echo "${dstname}:"
-
   if [[ -h "$dstname" ]]; then
-    echo -en "\tRemoving ... "
-    \rm -- "${dstname}" && echo "[OK] "
+    if [[ $(readlink $dstname) != $srcname ]]; then
+      \ln -sfv -- "$srcname" "$dstname"
+    fi
+
   elif [[ -e "$dstname" ]]; then
-    echo -en "\tMoving to ${dstname}.backup.$(date -I) ... "
-    \mv -- "${dstname}" "${dstname}.backup.$(date -I)" && echo "[OK]"
+    \mv -v -- "$dstname" "$dstname.backup.$(date -I)"
+    \ln -sv -- "$srcname" "$dstname"
+
+  else
+    \ln -sv -- "$srcname" "$dstname"
   fi
-  echo -en "\tSymlinking -> ${srcname} ... "
-  \ln -s -- "${srcname}" "${dstname}"
-  echo "[OK]"
 done
 
-if [[ ! -f $HOME/.bash_profile ]]; then
-  echo "source .bashrc" >> $HOME/.bash_profile
+if [[ ! -e $HOME/.bash_profile ]]; then
+  echo "source .bashrc" > $HOME/.bash_profile
 fi
 
-cd - >/dev/null
+\cd $start_pwd
 
